### ISSUE TITLE
"Bucket Shorty not found" Error message on first request

### ISSUE THREAD

**Issue by chrismalek** [makkes/shorty#3]
I downloaded, built and ran shorty. However on the first request it is saying the bucket cannot be found.

```
2016/07/27 12:29:54 Shorty listening on localhost:3002
2016/07/27 12:30:10 Bucket shorty not found
2016/07/27 12:30:10 Bucket shorty not found
2016/07/27 12:30:10 Bucket shorty not found
```

**Comment by chrismalek** [comment]
It is still an issue. I see a 400 coming back now but we are suffering from a chicken and egg probelm. How do you get your first URL in the DB?  http://localhost:3002/ does not work.

**Comment by makkes** [comment]
Thanks, @chrismalek, for your feedback. I added a README now which should make things clear. Shorty has the endpoint `/shorten?url=<URL>` with which you shorten a URL. It will return the shortened URL that you can use from then on.
